version: "3.6"
services:
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "9494:9494"
  mongodb:
    container_name: mongodb
    image: mongo:3.7.9-xenial
    ports:
      - "5672:5672"
  login-api:
    container_name: login-api
    build:
      context: ./login-api
      dockerfile: dev.Dockerfile
    volumes:
      - ./login-api:/app:rw
      - node_modules-login-api:/app/node_modules/
volumes:
  node_modules-login-api:
